name: hatyan_env
dependencies:
  - python>=3.8
  - pip>=19.2.3
  - pip:
    - scipy>=1.5.4
    - numpy>=1.18.4
    - matplotlib>=3.2.1
    - pandas>=1.2.0
    - netCDF4>=1.5.3
    - pyproj>=2.2.0
    - sip>=4.19.8
    - requests
    - statsmodels
    - xarray
